# Generated by Django 3.1.7 on 2021-05-13 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_subject_total_lec_alloted'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.teacher', to_field='teacher_id')),
            ],
        ),
    ]
