# Generated by Django 3.1.7 on 2021-05-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_studentattendance_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='subject',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
